#Requires -Version 5.1
<#
.SYNOPSIS
    Updates image references in HTML and Markdown files with WebP extensions and dimensions.

.DESCRIPTION
    This script finds all image references in HTML and Markdown files and updates them to:
    - Use .webp extension
    - Include width and height attributes
    - Add loading attributes (eager/lazy based on position)
    - Add fetchpriority for critical images

    Reads image metadata from image-metadata.json generated by optimize-images.ps1

.PARAMETER WhatIf
    Shows what changes would be made without actually making them

.PARAMETER AddLoadingAttributes
    Add loading="eager/lazy" attributes based on image type

.PARAMETER AddFetchPriority
    Add fetchpriority="high" for hero/LCP images

.EXAMPLE
    .\update-image-references.ps1
    Updates all image references with dimensions

.EXAMPLE
    .\update-image-references.ps1 -WhatIf
    Preview changes without modifying files

.EXAMPLE
    .\update-image-references.ps1 -AddLoadingAttributes -AddFetchPriority
    Update with all performance attributes
#>

param(
    [Parameter()]
    [switch]$WhatIf,

    [Parameter()]
    [switch]$AddLoadingAttributes,

    [Parameter()]
    [switch]$AddFetchPriority
)

$ErrorActionPreference = 'Stop'

# Color output functions
function Write-ColorOutput {
    param([string]$Message, [string]$Color = 'White')
    $colors = @{
        'Red'    = [ConsoleColor]::Red
        'Green'  = [ConsoleColor]::Green
        'Yellow' = [ConsoleColor]::Yellow
        'Cyan'   = [ConsoleColor]::Cyan
        'White'  = [ConsoleColor]::White
    }
    Write-Host $Message -ForegroundColor $colors[$Color]
}

Write-ColorOutput "`n=== Update Image References ===" 'Cyan'
if ($WhatIf) {
    Write-ColorOutput "Mode: Preview only (no changes will be made)" 'Yellow'
}

# Load image metadata
$metadataPath = Join-Path $PSScriptRoot '..\assets\images\image-metadata.json'
if (-not (Test-Path $metadataPath)) {
    Write-ColorOutput "`nERROR: Image metadata not found at: $metadataPath" 'Red'
    Write-ColorOutput 'Please run optimize-images.ps1 first to generate metadata' 'Yellow'
    exit 1
}

$metadata = Get-Content $metadataPath -Raw | ConvertFrom-Json
Write-ColorOutput "Loaded metadata for $($metadata.Images.Count) images" 'Green'
Write-ColorOutput "Last updated: $($metadata.LastUpdated)`n" 'White'

# Get all HTML and Markdown files
$rootPath = Split-Path $PSScriptRoot -Parent
$contentFiles = Get-ChildItem -Path $rootPath -Include *.html,*.md -Recurse -File |
    Where-Object { $_.FullName -notmatch '\\node_modules\\|\\vendor\\|\\_site\\|\\.git\\' }

Write-ColorOutput "Found $($contentFiles.Count) files to process`n" 'Cyan'

$totalUpdates = 0
$filesModified = 0

foreach ($file in $contentFiles) {
    $relativePath = $file.FullName.Replace("$rootPath\", '')
    $content = Get-Content $file.FullName -Raw
    $originalContent = $content
    $fileUpdateCount = 0

    # Process each image in metadata
    foreach ($imageInfo in $metadata.Images) {
        $imagePath = $imageInfo.Path
        $imageFileName = [System.IO.Path]::GetFileName($imagePath)
        $imageFileNameNoExt = [System.IO.Path]::GetFileNameWithoutExtension($imagePath)

        # Find original extensions that might be referenced
        $possibleExtensions = @('.jpg', '.jpeg', '.png')

        foreach ($ext in $possibleExtensions) {
            $originalFileName = $imageFileNameNoExt + $ext

            # Pattern 1: <img> tag with src but no dimensions
            $pattern1 = '(<img[^>]*?src="[^"]*?)' + [regex]::Escape($originalFileName) + '("(?![^>]*?width=)[^>]*?)>'

            if ($content -match $pattern1) {
                $replacement = '${1}' + $imageFileName + '${2} width="' + $imageInfo.Width + '" height="' + $imageInfo.Height + '"'

                # Add loading attribute if requested
                if ($AddLoadingAttributes) {
                    $loadingValue = if ($imageInfo.Type -eq 'Hero') { 'eager' } else { 'lazy' }
                    $replacement += ' loading="' + $loadingValue + '"'
                }

                # Add fetchpriority if requested and it's a hero image
                if ($AddFetchPriority -and $imageInfo.Type -eq 'Hero') {
                    $replacement += ' fetchpriority="high"'
                }

                $replacement += '>'

                $content = $content -replace $pattern1, $replacement
                $fileUpdateCount++
            }

            # Pattern 2: <img> tag with dimensions but wrong extension
            $pattern2 = '(<img[^>]*?src="[^"]*?)' + [regex]::Escape($originalFileName) + '("[^>]*?width=")(\d+)("[^>]*?height=")(\d+)("[^>]*?)>'

            if ($content -match $pattern2) {
                $replacement = '${1}' + $imageFileName + '${2}' + $imageInfo.Width + '${4}' + $imageInfo.Height + '${6}'

                # Add loading attribute if requested and not present
                if ($AddLoadingAttributes -and $content -notmatch 'loading=') {
                    $loadingValue = if ($imageInfo.Type -eq 'Hero') { 'eager' } else { 'lazy' }
                    $replacement += ' loading="' + $loadingValue + '"'
                }

                # Add fetchpriority if requested and it's a hero image
                if ($AddFetchPriority -and $imageInfo.Type -eq 'Hero' -and $content -notmatch 'fetchpriority=') {
                    $replacement += ' fetchpriority="high"'
                }

                $replacement += '>'

                $content = $content -replace $pattern2, $replacement
                $fileUpdateCount++
            }

            # Pattern 3: Markdown image syntax ![alt](path)
            $markdownPattern = '(!\[[^\]]*\]\([^)]*?)' + [regex]::Escape($originalFileName) + '(\))'

            if ($content -match $markdownPattern) {
                $replacement = '${1}' + $imageFileName + '${2}'
                $content = $content -replace $markdownPattern, $replacement
                $fileUpdateCount++
            }
        }
    }

    # Save changes if content was modified
    if ($content -ne $originalContent) {
        if (-not $WhatIf) {
            Set-Content $file.FullName -Value $content -NoNewline -Encoding UTF8
        }

        Write-ColorOutput "Updated: $relativePath" 'White'
        Write-ColorOutput "  Changes: $fileUpdateCount image reference(s)" 'Green'

        $totalUpdates += $fileUpdateCount
        $filesModified++
    }
}

# Summary
Write-ColorOutput "`n=== Update Summary ===" 'Cyan'
Write-ColorOutput "Files modified: $filesModified" 'White'
Write-ColorOutput "Total updates: $totalUpdates" 'Green'

if ($WhatIf) {
    Write-ColorOutput "`nRun without -WhatIf to apply changes" 'Yellow'
}
else {
    Write-ColorOutput "`nNext steps:" 'Cyan'
    Write-ColorOutput '1. Test the site locally to verify images display correctly' 'Yellow'
    Write-ColorOutput '2. Run validate-image-performance.ps1 to check compliance' 'Yellow'
    Write-ColorOutput '3. Commit changes to git' 'Yellow'
}

Write-ColorOutput "`n=== Complete ===" 'Cyan'
